### PR TITLE
Adding a Pytorch version

### PR DESCRIPTION
**Pull request by alexis-jacq**
Please find a Pytorch version of the reinforcement learning tutorial, if some of us want to try this library for RL. The structure is exactly the same, just some changes to build the models. I provide a suggestion of solution that solves the different exercise steps of the tutorial.

### CODE REVIEW

**Comment by oddskool** [comment]
Thank you for this version :)

If you want to merge it please
- remove all execution traces from the exercises notebook
- remove your solution notebook

**Comment by alexis-jacq** [comment]
I've removed execution traces and the solution notebook in this last commit.

**Comment by oddskool** [comment]
It seems the recommended way to install pytorch should be via:
`conda install pytorch torchvision -c pytorch`
I'm unable to make it work if I install using pip on OSX :(
Which way did you install it ?

**Comment by oddskool** [comment]
I tested this version and everything seems fine. We could merge it after we figure out the recommended setup instructions for pytorch.

**Comment by alexis-jacq** [comment]
On the main page of Pytorch, they say "Anaconda is our recommended package manager", I think that's the most stable way to install it.

**Pull request merged**
